//
//  BookDetailModels.swift
//  BookFinder
//
//  Created by CNOO on 2021/09/29.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BookDetail
{
  // MARK: Use cases
  
  enum BookInfo
  {
    struct Request
    {
    }
    struct Response
    {
        var book: Book
    }
    struct ViewModel
    {
        var book: Book
    }
  }
}
