//
//  BookDetailPresenter.swift
//  BookFinder
//
//  Created by CNOO on 2021/09/29.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailPresentationLogic
{
  func presentBookDetail(response: BookDetail.BookInfo.Response)
}

class BookDetailPresenter: BookDetailPresentationLogic
{
  weak var viewController: BookDetailDisplayLogic?
  
  // MARK: presentBookDetail
  
  func presentBookDetail(response: BookDetail.BookInfo.Response)
  {
    let viewModel = BookDetail.BookInfo.ViewModel(book: response.book)
    viewController?.displayBookDetail(viewModel: viewModel)
  }
}
