//
//  BookDetailInteractor.swift
//  BookFinder
//
//  Created by CNOO on 2021/09/29.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailBusinessLogic
{
    func loadBookDetail(request: BookDetail.BookInfo.Request)
}

protocol BookDetailDataStore
{
    var book: Book! { get set }
}

class BookDetailInteractor: BookDetailBusinessLogic, BookDetailDataStore
{
    var book: Book!
    
    var presenter: BookDetailPresentationLogic?
//    var worker: BookDetailWorker?
    
    // MARK: loadBookDetail
    
    func loadBookDetail(request: BookDetail.BookInfo.Request)
    {
        let response = BookDetail.BookInfo.Response(book: book)
        presenter?.presentBookDetail(response: response)
    }
}
