//
//  BookListInteractor.swift
//  BookFinder
//
//  Created by 18101004 on 2021/09/27.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListBusinessLogic
{
    func fetchBooks(request: BookList.FetchBooks.Request)
}

protocol BookListDataStore
{
    var books: [Book]? { get }
}

class BookListInteractor: BookListBusinessLogic, BookListDataStore
{
    var presenter: BookListPresentationLogic?
    
    var bookListWorker = BookListWorker()
    var books: [Book]?
    
    // MARK: fetch books
    
    func fetchBooks(request: BookList.FetchBooks.Request)
    {
        bookListWorker.fetchBooks(request: request) { result in
            switch result {
            case .success(let response):
                print(response)
                DispatchQueue.main.async {
                    self.presenter?.presentFetchedBooks(response: response)
                }
            case .failure(let error):
                debugPrint("🆘 \(error)")
            }
        }
    }
}
