//
//  BookListPresenter.swift
//  BookFinder
//
//  Created by 18101004 on 2021/09/27.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListPresentationLogic
{
    func presentFetchedBooks(response: BookList.FetchBooks.Response)
}

class BookListPresenter: BookListPresentationLogic
{
    weak var viewController: BookListDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedBooks(response: BookList.FetchBooks.Response)
    {
        var displayedBooks: [BookList.FetchBooks.ViewModel.DisplayedBook] = []
        
        response.items?.forEach {
            let displayBook = BookList.FetchBooks.ViewModel
                .DisplayedBook(id: $0.id,
                               imageUrl: $0.volumeInfo?.imageLinks?.thumbnail ?? "",
                               title: $0.volumeInfo?.title ?? "",
                               author: $0.volumeInfo?.authors?.joined(separator: ", ") ?? "",
                               date: $0.volumeInfo?.publishedDate ?? "")
            
            displayedBooks.append(displayBook)
        }
        
        let viewModel = BookList.FetchBooks.ViewModel(
            displayedBooks: displayedBooks,
            totalItemCnt: response.totalItems
        )
        
        viewController?.displayFetchedBooks(viewModel: viewModel)
    }
}
