//
//  BookListPresenter.swift
//  BookFinder
//
//  Created by 18101004 on 2021/09/27.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListPresentationLogic
{
  func presentSomething(response: BookList.Something.Response)
}

class BookListPresenter: BookListPresentationLogic
{
  weak var viewController: BookListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: BookList.Something.Response)
  {
    let viewModel = BookList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
