//
//  BookListViewController.swift
//  BookFinder
//
//  Created by 18101004 on 2021/09/27.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Combine

protocol BookListDisplayLogic: AnyObject
{
    func displayFetchedBooks(viewModel: BookList.FetchBooks.ViewModel)
}

class BookListViewController: UITableViewController, BookListDisplayLogic, UISearchBarDelegate
{
    var interactor: BookListBusinessLogic?
    var router: (NSObjectProtocol & BookListRoutingLogic & BookListDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = BookListInteractor()
        let presenter = BookListPresenter()
        let router = BookListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        
        setupUI()
    }
    
    private var bag = Set<AnyCancellable>()
    private func setupUI() {
        
        // Navigation
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationItem.largeTitleDisplayMode = .automatic
        
        // SEARCHBAR
        let searchController = UISearchController(searchResultsController: nil)
        searchController.searchBar.delegate = self
        searchController.hidesNavigationBarDuringPresentation = true
        navigationItem.hidesSearchBarWhenScrolling = true
        searchController.searchBar.sizeToFit()
        searchController.searchBar.returnKeyType = UIReturnKeyType.done
        searchController.searchBar.placeholder = "ex) type words to search..."
        navigationItem.searchController = searchController
        
        // Bind Searchbar
        let publisher = NotificationCenter.default.publisher(for: UISearchTextField.textDidChangeNotification, object: searchController.searchBar.searchTextField)
        
        publisher
            .map { $0.object as? UISearchTextField }
            .map { $0?.text }
            .compactMap{ $0 }
            .debounce(for: .milliseconds(100), scheduler: RunLoop.main)
            .sink(receiveValue: fetchBooks)
            .store(in: &bag)
    }
    
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
    }
    
    // MARK: - Fetch orders
    var displayedBooks: [BookList.FetchBooks.ViewModel.DisplayedBook] = []
    
    func fetchBooks(queryText: String)
    {
        let request = BookList.FetchBooks.Request(queryText: queryText, startIndex: 0)
        interactor?.fetchBooks(request: request)
//        let request = ListOrders.FetchOrders.Request()
//        interactor?.fetchOrders(request: request)
    }
    
    func displayFetchedBooks(viewModel: BookList.FetchBooks.ViewModel)
    {
        tableView.headerView(forSection: 0)?.textLabel?.text = "results (\(viewModel.totalItemCnt))"
        displayedBooks =  viewModel.displayedBooks
        tableView.reloadData()
        
    }
    
    // MARK: - Table view data source
    override func numberOfSections(in tableView: UITableView) -> Int { 1 }
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        displayedBooks.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let cell = tableView.dequeueReusableCell(withIdentifier: "BookListTableViewCell", for: indexPath) as! BookListTableViewCell
        cell.bindData(data: displayedBooks[indexPath.row])
        return cell
    }
   
}
