//
//  BookListInteractor.swift
//  BookFinder
//
//  Created by 18101004 on 2021/09/27.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListBusinessLogic
{
  func doSomething(request: BookList.Something.Request)
}

protocol BookListDataStore
{
  //var name: String { get set }
}

class BookListInteractor: BookListBusinessLogic, BookListDataStore
{
  var presenter: BookListPresentationLogic?
  var worker: BookListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BookList.Something.Request)
  {
    worker = BookListWorker()
    worker?.doSomeWork()
    
    let response = BookList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
