//
//  BookListModels.swift
//  BookFinder
//
//  Created by CNOO on 2021/09/27.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BookList
{
    // MARK: Use cases
    enum CellType {
        case data, fetching, search, empty, error, end
    }
    enum FetchBooks
    {
        struct Request
        {
            var queryText: String
            var startIndex: Int
            var maxResult: Int
        }
        struct Response: Codable
        {
            var kind: String
            var totalItems: Int
            var items: [Book]?
        }
        struct ViewModel
        {
            struct DisplayedBook {
                var state: CellType
                let imageUrl: String
                let title: String
                let author: String
                let date: String
                
                init(state: CellType) {
                    self.init(imageUrl: "", title: "", author: "", date: "")
                    self.state = state
                }
                
                init(
                    imageUrl: String,
                    title: String,
                    author: String,
                    date: String
                ) {
                    self.state = .data
                    self.imageUrl = imageUrl
                    self.title = title
                    self.author = author
                    self.date = date
                }
            }
            
            var displayedBooks: [DisplayedBook]
            var totalItemCnt: Int
        }
    }
}
