//
//  BookListInteractorTests.swift
//  BookFinder
//
//  Created by CNOO on 2021/09/29.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BookFinder
import XCTest

class BookListInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: BookListInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupBookListInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupBookListInteractor()
  {
    sut = BookListInteractor()
  }
  
  // MARK: Test doubles
  
  class BookListPresentationLogicSpy: BookListPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: BookList.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = BookListPresentationLogicSpy()
    sut.presenter = spy
    let request = BookList.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
